content:
    -
        type: HeroButton                           # 通知类型  必填
        date: "09:00"                              # 提醒时间  必填
        title: 工作前喝一杯水                     # 标题  必填
        body: 镇定精神，努力工作                   # 内容  必填
        icon: '/gg1.png'                     # 图标    选填
        image: '/water.gif'                                # 封面图
        duration: long                         # 参数 short、long  必填
        label: 逛逛掘金                          #  button按钮文案   选填
        launch: 'https://juejin.cn/pins/new'   # 跳转路径  选填
        audio:                                 # 音频文件  选填
    -
        type: HeroImage
        date: "10:34"
        title: 工作间隙喝一杯水
        body: 站会儿，放松情绪，补充水分
        icon: '/water.gif'
        image: '/water.gif'
        duration: long
        label:
        launch:
        audio:
    -
        type: HeroButton
        date: '15:00'
        title: 午餐后一小时一杯水
        body: 促进消化保持身材
        icon: '/water.gif'
        image: '/water.gif'
        duration: long
        label: 刷刷微博
        launch: "https://weibo.com/newlogin?tabtype=search&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2Ftv%2Fhome"
        audio:
    -
        type: HeroImage
        date: '16:00'
        title: 下午喝一杯水
        body: 起来走走，消除疲劳，振奋精神
        icon: '/water.gif'
        image: '/water.gif'
        duration: long
        label:
        launch:
        audio:
    -
        type: InlineButton
        date: '18:00'
        title: 快下班啦~~~
        body: 归家途中，喝水增加饱腹感
        icon: '/water.gif'
        image: '/water.gif'
        duration: long
        label: 刷刷微博
        launch: 'https://weibo.com/newlogin?tabtype=search&openLoginLayer=0&url=https%3A%2F%2Fweibo.com%2Ftv%2Fhome'
        audio:



MAIN:
  app_id: 'D:\Program Files (x86)\Tencent\WeChat\WeChat.exe'   # 应用图标  获取方式：管理员权限  输入：Get-StartApps 即可查询appid
  start_time: '09:10:00'   # 程序后台执行时间
  end_time: '18:10:00'     # 程序后台结束时间


